/* soapH.h
   Generated by gSOAP 2.8.0 from WS-Discovery.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_begin_send(soap) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef SOAP_TYPE_wsa3__RelationshipTypeValues
#define SOAP_TYPE_wsa3__RelationshipTypeValues (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa3__RelationshipTypeValues(struct soap*, enum wsa3__RelationshipTypeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa3__RelationshipTypeValues(struct soap*, const char*, int, const enum wsa3__RelationshipTypeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_wsa3__RelationshipTypeValues2s(struct soap*, enum wsa3__RelationshipTypeValues);
SOAP_FMAC3 enum wsa3__RelationshipTypeValues * SOAP_FMAC4 soap_in_wsa3__RelationshipTypeValues(struct soap*, const char*, enum wsa3__RelationshipTypeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2wsa3__RelationshipTypeValues(struct soap*, const char*, enum wsa3__RelationshipTypeValues *);

#ifndef soap_write_wsa3__RelationshipTypeValues
#define soap_write_wsa3__RelationshipTypeValues(soap, data) ( soap_begin_send(soap) || soap_put_wsa3__RelationshipTypeValues(soap, data, "wsa3:RelationshipTypeValues", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa3__RelationshipTypeValues(struct soap*, const enum wsa3__RelationshipTypeValues *, const char*, const char*);

#ifndef soap_read_wsa3__RelationshipTypeValues
#define soap_read_wsa3__RelationshipTypeValues(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa3__RelationshipTypeValues(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum wsa3__RelationshipTypeValues * SOAP_FMAC4 soap_get_wsa3__RelationshipTypeValues(struct soap*, enum wsa3__RelationshipTypeValues *, const char*, const char*);

/* _ns1__Scopes is a typedef element/attribute synonym for std__string */

#ifndef SOAP_TYPE__ns1__Scopes
#define SOAP_TYPE__ns1__Scopes (47)
#endif

#define soap_default__ns1__Scopes(soap, a) soap_default_std__string(soap, a)


#define soap_serialize__ns1__Scopes(soap, a) soap_serialize_std__string(soap, a)


#define soap_out__ns1__Scopes soap_out_std__string


#define soap_in__ns1__Scopes soap_in_std__string


#ifndef soap_write__ns1__Scopes
#define soap_write__ns1__Scopes(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Scopes", NULL) || soap_end_send(soap) )
#endif


#define soap_put__ns1__Scopes soap_put_std__string


#ifndef soap_read__ns1__Scopes
#define soap_read__ns1__Scopes(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Scopes(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__ns1__Scopes soap_get_std__string


#define soap_new__ns1__Scopes(soap, n) soap_instantiate__ns1__Scopes(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__Scopes(soap, p) soap_delete(soap, p)


#define soap_instantiate__ns1__Scopes soap_instantiate_std__string


#define soap_copy__ns1__Scopes soap_copy_std__string

/* _ns1__Types is a typedef element/attribute synonym for std__string */

#ifndef SOAP_TYPE__ns1__Types
#define SOAP_TYPE__ns1__Types (46)
#endif

#define soap_default__ns1__Types(soap, a) soap_default_std__string(soap, a)


#define soap_serialize__ns1__Types(soap, a) soap_serialize_std__string(soap, a)


#define soap_out__ns1__Types soap_out_std__string


#define soap_in__ns1__Types soap_in_std__string


#ifndef soap_write__ns1__Types
#define soap_write__ns1__Types(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Types", NULL) || soap_end_send(soap) )
#endif


#define soap_put__ns1__Types soap_put_std__string


#ifndef soap_read__ns1__Types
#define soap_read__ns1__Types(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Types(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__ns1__Types soap_get_std__string


#define soap_new__ns1__Types(soap, n) soap_instantiate__ns1__Types(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__Types(soap, p) soap_delete(soap, p)


#define soap_instantiate__ns1__Types soap_instantiate_std__string


#define soap_copy__ns1__Types soap_copy_std__string

#ifndef SOAP_TYPE__ns1__SoapHttpRequestReplyAddress
#define SOAP_TYPE__ns1__SoapHttpRequestReplyAddress (45)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SoapHttpRequestReplyAddress(struct soap*, const char*, int, const _ns1__SoapHttpRequestReplyAddress *, const char*);
SOAP_FMAC3 _ns1__SoapHttpRequestReplyAddress * SOAP_FMAC4 soap_in__ns1__SoapHttpRequestReplyAddress(struct soap*, const char*, _ns1__SoapHttpRequestReplyAddress *, const char*);

#ifndef soap_write__ns1__SoapHttpRequestReplyAddress
#define soap_write__ns1__SoapHttpRequestReplyAddress(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:SoapHttpRequestReplyAddress", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__SoapHttpRequestReplyAddress
#define soap_read__ns1__SoapHttpRequestReplyAddress(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__SoapHttpRequestReplyAddress(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__SoapHttpRequestReplyAddress * SOAP_FMAC4 soap_get__ns1__SoapHttpRequestReplyAddress(struct soap*, _ns1__SoapHttpRequestReplyAddress *, const char*, const char*);

#define soap_new__ns1__SoapHttpRequestReplyAddress(soap, n) soap_instantiate__ns1__SoapHttpRequestReplyAddress(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__SoapHttpRequestReplyAddress(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__SoapHttpRequestReplyAddress * SOAP_FMAC2 soap_instantiate__ns1__SoapHttpRequestReplyAddress(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SoapHttpRequestReplyAddress(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__AppSequence
#define SOAP_TYPE__ns1__AppSequence (44)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__AppSequence(struct soap*, const char*, int, const _ns1__AppSequence *, const char*);
SOAP_FMAC3 _ns1__AppSequence * SOAP_FMAC4 soap_in__ns1__AppSequence(struct soap*, const char*, _ns1__AppSequence *, const char*);

#ifndef soap_write__ns1__AppSequence
#define soap_write__ns1__AppSequence(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:AppSequence", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__AppSequence
#define soap_read__ns1__AppSequence(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__AppSequence(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__AppSequence * SOAP_FMAC4 soap_get__ns1__AppSequence(struct soap*, _ns1__AppSequence *, const char*, const char*);

#define soap_new__ns1__AppSequence(soap, n) soap_instantiate__ns1__AppSequence(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__AppSequence(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__AppSequence * SOAP_FMAC2 soap_instantiate__ns1__AppSequence(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__AppSequence(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Scope
#define SOAP_TYPE__ns1__Scope (43)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Scope(struct soap*, const char*, int, const _ns1__Scope *, const char*);
SOAP_FMAC3 _ns1__Scope * SOAP_FMAC4 soap_in__ns1__Scope(struct soap*, const char*, _ns1__Scope *, const char*);

#ifndef soap_write__ns1__Scope
#define soap_write__ns1__Scope(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Scope", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__Scope
#define soap_read__ns1__Scope(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Scope(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__Scope * SOAP_FMAC4 soap_get__ns1__Scope(struct soap*, _ns1__Scope *, const char*, const char*);

#define soap_new__ns1__Scope(soap, n) soap_instantiate__ns1__Scope(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__Scope(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__Scope * SOAP_FMAC2 soap_instantiate__ns1__Scope(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Scope(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Probe
#define SOAP_TYPE__ns1__Probe (42)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Probe(struct soap*, const char*, int, const _ns1__Probe *, const char*);
SOAP_FMAC3 _ns1__Probe * SOAP_FMAC4 soap_in__ns1__Probe(struct soap*, const char*, _ns1__Probe *, const char*);

#ifndef soap_write__ns1__Probe
#define soap_write__ns1__Probe(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Probe", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__Probe
#define soap_read__ns1__Probe(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Probe(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__Probe * SOAP_FMAC4 soap_get__ns1__Probe(struct soap*, _ns1__Probe *, const char*, const char*);

#define soap_new__ns1__Probe(soap, n) soap_instantiate__ns1__Probe(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__Probe(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__Probe * SOAP_FMAC2 soap_instantiate__ns1__Probe(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Probe(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Bye
#define SOAP_TYPE__ns1__Bye (41)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Bye(struct soap*, const char*, int, const _ns1__Bye *, const char*);
SOAP_FMAC3 _ns1__Bye * SOAP_FMAC4 soap_in__ns1__Bye(struct soap*, const char*, _ns1__Bye *, const char*);

#ifndef soap_write__ns1__Bye
#define soap_write__ns1__Bye(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Bye", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__Bye
#define soap_read__ns1__Bye(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Bye(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__Bye * SOAP_FMAC4 soap_get__ns1__Bye(struct soap*, _ns1__Bye *, const char*, const char*);

#define soap_new__ns1__Bye(soap, n) soap_instantiate__ns1__Bye(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__Bye(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__Bye * SOAP_FMAC2 soap_instantiate__ns1__Bye(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Bye(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__DiscoveryReferenceType
#define SOAP_TYPE_ns1__DiscoveryReferenceType (40)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DiscoveryReferenceType(struct soap*, const char*, int, const ns1__DiscoveryReferenceType *, const char*);
SOAP_FMAC3 ns1__DiscoveryReferenceType * SOAP_FMAC4 soap_in_ns1__DiscoveryReferenceType(struct soap*, const char*, ns1__DiscoveryReferenceType *, const char*);

#ifndef soap_write_ns1__DiscoveryReferenceType
#define soap_write_ns1__DiscoveryReferenceType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:DiscoveryReferenceType", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__DiscoveryReferenceType
#define soap_read_ns1__DiscoveryReferenceType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__DiscoveryReferenceType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__DiscoveryReferenceType * SOAP_FMAC4 soap_get_ns1__DiscoveryReferenceType(struct soap*, ns1__DiscoveryReferenceType *, const char*, const char*);

#define soap_new_ns1__DiscoveryReferenceType(soap, n) soap_instantiate_ns1__DiscoveryReferenceType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__DiscoveryReferenceType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__DiscoveryReferenceType * SOAP_FMAC2 soap_instantiate_ns1__DiscoveryReferenceType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__DiscoveryReferenceType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__positiveInteger_
#define SOAP_TYPE_xsd__positiveInteger_ (39)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__positiveInteger_(struct soap*, const char*, int, const xsd__positiveInteger_ *, const char*);
SOAP_FMAC3 xsd__positiveInteger_ * SOAP_FMAC4 soap_in_xsd__positiveInteger_(struct soap*, const char*, xsd__positiveInteger_ *, const char*);

#ifndef soap_write_xsd__positiveInteger_
#define soap_write_xsd__positiveInteger_(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:positiveInteger", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_xsd__positiveInteger_
#define soap_read_xsd__positiveInteger_(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__positiveInteger_(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 xsd__positiveInteger_ * SOAP_FMAC4 soap_get_xsd__positiveInteger_(struct soap*, xsd__positiveInteger_ *, const char*, const char*);

#define soap_new_xsd__positiveInteger_(soap, n) soap_instantiate_xsd__positiveInteger_(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__positiveInteger_(soap, p) soap_delete(soap, p)

SOAP_FMAC1 xsd__positiveInteger_ * SOAP_FMAC2 soap_instantiate_xsd__positiveInteger_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__positiveInteger_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__positiveInteger
#define SOAP_TYPE_xsd__positiveInteger (38)
#endif

#define soap_default_xsd__positiveInteger(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__positiveInteger(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__positiveInteger(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__positiveInteger(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_xsd__positiveInteger
#define soap_write_xsd__positiveInteger(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:positiveInteger", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__positiveInteger(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_xsd__positiveInteger
#define soap_read_xsd__positiveInteger(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__positiveInteger(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__positiveInteger(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__positiveInteger(soap, n) soap_instantiate_xsd__positiveInteger(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__positiveInteger(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__positiveInteger soap_instantiate_std__string


#define soap_copy_xsd__positiveInteger soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__nonNegativeInteger
#define SOAP_TYPE_xsd__nonNegativeInteger (35)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonNegativeInteger(struct soap*, const char*, int, const xsd__nonNegativeInteger *, const char*);
SOAP_FMAC3 xsd__nonNegativeInteger * SOAP_FMAC4 soap_in_xsd__nonNegativeInteger(struct soap*, const char*, xsd__nonNegativeInteger *, const char*);

#ifndef soap_write_xsd__nonNegativeInteger
#define soap_write_xsd__nonNegativeInteger(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:nonNegativeInteger", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_xsd__nonNegativeInteger
#define soap_read_xsd__nonNegativeInteger(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__nonNegativeInteger(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 xsd__nonNegativeInteger * SOAP_FMAC4 soap_get_xsd__nonNegativeInteger(struct soap*, xsd__nonNegativeInteger *, const char*, const char*);

#define soap_new_xsd__nonNegativeInteger(soap, n) soap_instantiate_xsd__nonNegativeInteger(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__nonNegativeInteger(soap, p) soap_delete(soap, p)

SOAP_FMAC1 xsd__nonNegativeInteger * SOAP_FMAC2 soap_instantiate_xsd__nonNegativeInteger(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__nonNegativeInteger(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (34)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, const xsd__anyURI *, const char*);
SOAP_FMAC3 xsd__anyURI * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, xsd__anyURI *, const char*);

#ifndef soap_write_xsd__anyURI
#define soap_write_xsd__anyURI(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:anyURI", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_xsd__anyURI
#define soap_read_xsd__anyURI(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__anyURI(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 xsd__anyURI * SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, xsd__anyURI *, const char*, const char*);

#define soap_new_xsd__anyURI(soap, n) soap_instantiate_xsd__anyURI(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__anyURI(soap, p) soap_delete(soap, p)

SOAP_FMAC1 xsd__anyURI * SOAP_FMAC2 soap_instantiate_xsd__anyURI(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyURI(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__QName
#define SOAP_TYPE_xsd__QName (33)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__QName(struct soap*, const char*, int, const xsd__QName *, const char*);
SOAP_FMAC3 xsd__QName * SOAP_FMAC4 soap_in_xsd__QName(struct soap*, const char*, xsd__QName *, const char*);

#ifndef soap_write_xsd__QName
#define soap_write_xsd__QName(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:QName", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_xsd__QName
#define soap_read_xsd__QName(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 xsd__QName * SOAP_FMAC4 soap_get_xsd__QName(struct soap*, xsd__QName *, const char*, const char*);

#define soap_new_xsd__QName(soap, n) soap_instantiate_xsd__QName(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__QName(soap, p) soap_delete(soap, p)

SOAP_FMAC1 xsd__QName * SOAP_FMAC2 soap_instantiate_xsd__QName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__QName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (31)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyType(struct soap*, const char*, int, const xsd__anyType *, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_in_xsd__anyType(struct soap*, const char*, xsd__anyType *, const char*);

#ifndef soap_write_xsd__anyType
#define soap_write_xsd__anyType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:anyType", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_xsd__anyType
#define soap_read_xsd__anyType(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__anyType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, xsd__anyType *, const char*, const char*);

#define soap_new_xsd__anyType(soap, n) soap_instantiate_xsd__anyType(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__anyType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 xsd__anyType * SOAP_FMAC2 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* _wsa3__Recipient is a typedef element/attribute synonym for wsa3__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa3__Recipient
#define SOAP_TYPE__wsa3__Recipient (25)
#endif

#define soap_default__wsa3__Recipient(soap, a) soap_default_wsa3__EndpointReferenceType(soap, a)


#define soap_serialize__wsa3__Recipient(soap, a) soap_serialize_wsa3__EndpointReferenceType(soap, a)


#define soap_out__wsa3__Recipient soap_out_wsa3__EndpointReferenceType


#define soap_in__wsa3__Recipient soap_in_wsa3__EndpointReferenceType


#ifndef soap_write__wsa3__Recipient
#define soap_write__wsa3__Recipient(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__Recipient(soap, data), 0) || soap_put__wsa3__Recipient(soap, data, "wsa3:Recipient", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__Recipient soap_put_wsa3__EndpointReferenceType


#ifndef soap_read__wsa3__Recipient
#define soap_read__wsa3__Recipient(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__Recipient(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__Recipient soap_get_wsa3__EndpointReferenceType


#define soap_new__wsa3__Recipient(soap, n) soap_instantiate__wsa3__Recipient(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa3__Recipient(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa3__Recipient soap_instantiate_wsa3__EndpointReferenceType


#define soap_copy__wsa3__Recipient soap_copy_wsa3__EndpointReferenceType

/* _wsa3__FaultTo is a typedef element/attribute synonym for wsa3__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa3__FaultTo
#define SOAP_TYPE__wsa3__FaultTo (24)
#endif

#define soap_default__wsa3__FaultTo(soap, a) soap_default_wsa3__EndpointReferenceType(soap, a)


#define soap_serialize__wsa3__FaultTo(soap, a) soap_serialize_wsa3__EndpointReferenceType(soap, a)


#define soap_out__wsa3__FaultTo soap_out_wsa3__EndpointReferenceType


#define soap_in__wsa3__FaultTo soap_in_wsa3__EndpointReferenceType


#ifndef soap_write__wsa3__FaultTo
#define soap_write__wsa3__FaultTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__FaultTo(soap, data), 0) || soap_put__wsa3__FaultTo(soap, data, "wsa3:FaultTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__FaultTo soap_put_wsa3__EndpointReferenceType


#ifndef soap_read__wsa3__FaultTo
#define soap_read__wsa3__FaultTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__FaultTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__FaultTo soap_get_wsa3__EndpointReferenceType


#define soap_new__wsa3__FaultTo(soap, n) soap_instantiate__wsa3__FaultTo(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa3__FaultTo(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa3__FaultTo soap_instantiate_wsa3__EndpointReferenceType


#define soap_copy__wsa3__FaultTo soap_copy_wsa3__EndpointReferenceType

/* _wsa3__ReplyTo is a typedef element/attribute synonym for wsa3__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa3__ReplyTo
#define SOAP_TYPE__wsa3__ReplyTo (23)
#endif

#define soap_default__wsa3__ReplyTo(soap, a) soap_default_wsa3__EndpointReferenceType(soap, a)


#define soap_serialize__wsa3__ReplyTo(soap, a) soap_serialize_wsa3__EndpointReferenceType(soap, a)


#define soap_out__wsa3__ReplyTo soap_out_wsa3__EndpointReferenceType


#define soap_in__wsa3__ReplyTo soap_in_wsa3__EndpointReferenceType


#ifndef soap_write__wsa3__ReplyTo
#define soap_write__wsa3__ReplyTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__ReplyTo(soap, data), 0) || soap_put__wsa3__ReplyTo(soap, data, "wsa3:ReplyTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__ReplyTo soap_put_wsa3__EndpointReferenceType


#ifndef soap_read__wsa3__ReplyTo
#define soap_read__wsa3__ReplyTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__ReplyTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__ReplyTo soap_get_wsa3__EndpointReferenceType


#define soap_new__wsa3__ReplyTo(soap, n) soap_instantiate__wsa3__ReplyTo(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa3__ReplyTo(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa3__ReplyTo soap_instantiate_wsa3__EndpointReferenceType


#define soap_copy__wsa3__ReplyTo soap_copy_wsa3__EndpointReferenceType

/* _wsa3__From is a typedef element/attribute synonym for wsa3__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa3__From
#define SOAP_TYPE__wsa3__From (22)
#endif

#define soap_default__wsa3__From(soap, a) soap_default_wsa3__EndpointReferenceType(soap, a)


#define soap_serialize__wsa3__From(soap, a) soap_serialize_wsa3__EndpointReferenceType(soap, a)


#define soap_out__wsa3__From soap_out_wsa3__EndpointReferenceType


#define soap_in__wsa3__From soap_in_wsa3__EndpointReferenceType


#ifndef soap_write__wsa3__From
#define soap_write__wsa3__From(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__From(soap, data), 0) || soap_put__wsa3__From(soap, data, "wsa3:From", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__From soap_put_wsa3__EndpointReferenceType


#ifndef soap_read__wsa3__From
#define soap_read__wsa3__From(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__From(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__From soap_get_wsa3__EndpointReferenceType


#define soap_new__wsa3__From(soap, n) soap_instantiate__wsa3__From(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa3__From(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa3__From soap_instantiate_wsa3__EndpointReferenceType


#define soap_copy__wsa3__From soap_copy_wsa3__EndpointReferenceType

/* _wsa3__RelatesTo is a typedef element/attribute synonym for wsa3__Relationship */

#ifndef SOAP_TYPE__wsa3__RelatesTo
#define SOAP_TYPE__wsa3__RelatesTo (19)
#endif

#define soap_default__wsa3__RelatesTo(soap, a) soap_default_wsa3__Relationship(soap, a)


#define soap_serialize__wsa3__RelatesTo(soap, a) soap_serialize_wsa3__Relationship(soap, a)


#define soap_out__wsa3__RelatesTo soap_out_wsa3__Relationship


#define soap_in__wsa3__RelatesTo soap_in_wsa3__Relationship


#ifndef soap_write__wsa3__RelatesTo
#define soap_write__wsa3__RelatesTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__RelatesTo(soap, data), 0) || soap_put__wsa3__RelatesTo(soap, data, "wsa3:RelatesTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__RelatesTo soap_put_wsa3__Relationship


#ifndef soap_read__wsa3__RelatesTo
#define soap_read__wsa3__RelatesTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__RelatesTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__RelatesTo soap_get_wsa3__Relationship


#define soap_new__wsa3__RelatesTo(soap, n) soap_instantiate__wsa3__RelatesTo(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa3__RelatesTo(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa3__RelatesTo soap_instantiate_wsa3__Relationship


#define soap_copy__wsa3__RelatesTo soap_copy_wsa3__Relationship

/* _wsa3__EndpointReference is a typedef element/attribute synonym for wsa3__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa3__EndpointReference
#define SOAP_TYPE__wsa3__EndpointReference (17)
#endif

#define soap_default__wsa3__EndpointReference(soap, a) soap_default_wsa3__EndpointReferenceType(soap, a)


#define soap_serialize__wsa3__EndpointReference(soap, a) soap_serialize_wsa3__EndpointReferenceType(soap, a)


#define soap_out__wsa3__EndpointReference soap_out_wsa3__EndpointReferenceType


#define soap_in__wsa3__EndpointReference soap_in_wsa3__EndpointReferenceType


#ifndef soap_write__wsa3__EndpointReference
#define soap_write__wsa3__EndpointReference(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__EndpointReference(soap, data), 0) || soap_put__wsa3__EndpointReference(soap, data, "wsa3:EndpointReference", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__EndpointReference soap_put_wsa3__EndpointReferenceType


#ifndef soap_read__wsa3__EndpointReference
#define soap_read__wsa3__EndpointReference(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__EndpointReference(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__EndpointReference soap_get_wsa3__EndpointReferenceType


#define soap_new__wsa3__EndpointReference(soap, n) soap_instantiate__wsa3__EndpointReference(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa3__EndpointReference(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa3__EndpointReference soap_instantiate_wsa3__EndpointReferenceType


#define soap_copy__wsa3__EndpointReference soap_copy_wsa3__EndpointReferenceType

#ifndef SOAP_TYPE_wsa3__Relationship
#define SOAP_TYPE_wsa3__Relationship (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa3__Relationship(struct soap*, struct wsa3__Relationship *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa3__Relationship(struct soap*, const struct wsa3__Relationship *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa3__Relationship(struct soap*, const char*, int, const struct wsa3__Relationship *, const char*);
SOAP_FMAC3 struct wsa3__Relationship * SOAP_FMAC4 soap_in_wsa3__Relationship(struct soap*, const char*, struct wsa3__Relationship *, const char*);

#ifndef soap_write_wsa3__Relationship
#define soap_write_wsa3__Relationship(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa3__Relationship(soap, data), 0) || soap_put_wsa3__Relationship(soap, data, "wsa3:Relationship", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa3__Relationship(struct soap*, const struct wsa3__Relationship *, const char*, const char*);

#ifndef soap_read_wsa3__Relationship
#define soap_read_wsa3__Relationship(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa3__Relationship(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__Relationship * SOAP_FMAC4 soap_get_wsa3__Relationship(struct soap*, struct wsa3__Relationship *, const char*, const char*);

#define soap_new_wsa3__Relationship(soap, n) soap_instantiate_wsa3__Relationship(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa3__Relationship(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa3__Relationship * SOAP_FMAC2 soap_instantiate_wsa3__Relationship(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa3__Relationship(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsa3__ServiceNameType
#define SOAP_TYPE_wsa3__ServiceNameType (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa3__ServiceNameType(struct soap*, struct wsa3__ServiceNameType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa3__ServiceNameType(struct soap*, const struct wsa3__ServiceNameType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa3__ServiceNameType(struct soap*, const char*, int, const struct wsa3__ServiceNameType *, const char*);
SOAP_FMAC3 struct wsa3__ServiceNameType * SOAP_FMAC4 soap_in_wsa3__ServiceNameType(struct soap*, const char*, struct wsa3__ServiceNameType *, const char*);

#ifndef soap_write_wsa3__ServiceNameType
#define soap_write_wsa3__ServiceNameType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa3__ServiceNameType(soap, data), 0) || soap_put_wsa3__ServiceNameType(soap, data, "wsa3:ServiceNameType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa3__ServiceNameType(struct soap*, const struct wsa3__ServiceNameType *, const char*, const char*);

#ifndef soap_read_wsa3__ServiceNameType
#define soap_read_wsa3__ServiceNameType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa3__ServiceNameType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__ServiceNameType * SOAP_FMAC4 soap_get_wsa3__ServiceNameType(struct soap*, struct wsa3__ServiceNameType *, const char*, const char*);

#define soap_new_wsa3__ServiceNameType(soap, n) soap_instantiate_wsa3__ServiceNameType(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa3__ServiceNameType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa3__ServiceNameType * SOAP_FMAC2 soap_instantiate_wsa3__ServiceNameType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa3__ServiceNameType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsa3__ReferencePropertiesType
#define SOAP_TYPE_wsa3__ReferencePropertiesType (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa3__ReferencePropertiesType(struct soap*, struct wsa3__ReferencePropertiesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa3__ReferencePropertiesType(struct soap*, const struct wsa3__ReferencePropertiesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa3__ReferencePropertiesType(struct soap*, const char*, int, const struct wsa3__ReferencePropertiesType *, const char*);
SOAP_FMAC3 struct wsa3__ReferencePropertiesType * SOAP_FMAC4 soap_in_wsa3__ReferencePropertiesType(struct soap*, const char*, struct wsa3__ReferencePropertiesType *, const char*);

#ifndef soap_write_wsa3__ReferencePropertiesType
#define soap_write_wsa3__ReferencePropertiesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa3__ReferencePropertiesType(soap, data), 0) || soap_put_wsa3__ReferencePropertiesType(soap, data, "wsa3:ReferencePropertiesType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa3__ReferencePropertiesType(struct soap*, const struct wsa3__ReferencePropertiesType *, const char*, const char*);

#ifndef soap_read_wsa3__ReferencePropertiesType
#define soap_read_wsa3__ReferencePropertiesType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa3__ReferencePropertiesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__ReferencePropertiesType * SOAP_FMAC4 soap_get_wsa3__ReferencePropertiesType(struct soap*, struct wsa3__ReferencePropertiesType *, const char*, const char*);

#define soap_new_wsa3__ReferencePropertiesType(soap, n) soap_instantiate_wsa3__ReferencePropertiesType(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa3__ReferencePropertiesType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa3__ReferencePropertiesType * SOAP_FMAC2 soap_instantiate_wsa3__ReferencePropertiesType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa3__ReferencePropertiesType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsa3__EndpointReferenceType
#define SOAP_TYPE_wsa3__EndpointReferenceType (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa3__EndpointReferenceType(struct soap*, struct wsa3__EndpointReferenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa3__EndpointReferenceType(struct soap*, const struct wsa3__EndpointReferenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa3__EndpointReferenceType(struct soap*, const char*, int, const struct wsa3__EndpointReferenceType *, const char*);
SOAP_FMAC3 struct wsa3__EndpointReferenceType * SOAP_FMAC4 soap_in_wsa3__EndpointReferenceType(struct soap*, const char*, struct wsa3__EndpointReferenceType *, const char*);

#ifndef soap_write_wsa3__EndpointReferenceType
#define soap_write_wsa3__EndpointReferenceType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa3__EndpointReferenceType(soap, data), 0) || soap_put_wsa3__EndpointReferenceType(soap, data, "wsa3:EndpointReferenceType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa3__EndpointReferenceType(struct soap*, const struct wsa3__EndpointReferenceType *, const char*, const char*);

#ifndef soap_read_wsa3__EndpointReferenceType
#define soap_read_wsa3__EndpointReferenceType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa3__EndpointReferenceType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__EndpointReferenceType * SOAP_FMAC4 soap_get_wsa3__EndpointReferenceType(struct soap*, struct wsa3__EndpointReferenceType *, const char*, const char*);

#define soap_new_wsa3__EndpointReferenceType(soap, n) soap_instantiate_wsa3__EndpointReferenceType(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa3__EndpointReferenceType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa3__EndpointReferenceType * SOAP_FMAC2 soap_instantiate_wsa3__EndpointReferenceType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa3__EndpointReferenceType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__Scope
#define SOAP_TYPE_PointerTo_ns1__Scope (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Scope(struct soap*, _ns1__Scope *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Scope(struct soap*, const char *, int, _ns1__Scope *const*, const char *);
SOAP_FMAC3 _ns1__Scope ** SOAP_FMAC4 soap_in_PointerTo_ns1__Scope(struct soap*, const char*, _ns1__Scope **, const char*);

#ifndef soap_write_PointerTo_ns1__Scope
#define soap_write_PointerTo_ns1__Scope(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Scope(soap, data), 0) || soap_put_PointerTo_ns1__Scope(soap, data, "ns1:Scope", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Scope(struct soap*, _ns1__Scope *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Scope
#define soap_read_PointerTo_ns1__Scope(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Scope(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__Scope ** SOAP_FMAC4 soap_get_PointerTo_ns1__Scope(struct soap*, _ns1__Scope **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__Scopes
#define SOAP_TYPE_PointerTo_ns1__Scopes (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Scopes(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Scopes(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTo_ns1__Scopes(struct soap*, const char*, std::string **, const char*);

#ifndef soap_write_PointerTo_ns1__Scopes
#define soap_write_PointerTo_ns1__Scopes(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Scopes(soap, data), 0) || soap_put_PointerTo_ns1__Scopes(soap, data, "ns1:Scopes", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Scopes(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Scopes
#define soap_read_PointerTo_ns1__Scopes(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Scopes(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTo_ns1__Scopes(struct soap*, std::string **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__Types
#define SOAP_TYPE_PointerTo_ns1__Types (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Types(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Types(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTo_ns1__Types(struct soap*, const char*, std::string **, const char*);

#ifndef soap_write_PointerTo_ns1__Types
#define soap_write_PointerTo_ns1__Types(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Types(soap, data), 0) || soap_put_PointerTo_ns1__Types(soap, data, "ns1:Types", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Types(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Types
#define soap_read_PointerTo_ns1__Types(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Types(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTo_ns1__Types(struct soap*, std::string **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa3__FaultTo
#define SOAP_TYPE_PointerTo_wsa3__FaultTo (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa3__FaultTo(struct soap*, struct wsa3__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa3__FaultTo(struct soap*, const char *, int, struct wsa3__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa3__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa3__FaultTo(struct soap*, const char*, struct wsa3__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa3__FaultTo
#define soap_write_PointerTo_wsa3__FaultTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa3__FaultTo(soap, data), 0) || soap_put_PointerTo_wsa3__FaultTo(soap, data, "wsa3:FaultTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa3__FaultTo(struct soap*, struct wsa3__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa3__FaultTo
#define soap_read_PointerTo_wsa3__FaultTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa3__FaultTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa3__FaultTo(struct soap*, struct wsa3__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa3__ReplyTo
#define SOAP_TYPE_PointerTo_wsa3__ReplyTo (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa3__ReplyTo(struct soap*, struct wsa3__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa3__ReplyTo(struct soap*, const char *, int, struct wsa3__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa3__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa3__ReplyTo(struct soap*, const char*, struct wsa3__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa3__ReplyTo
#define soap_write_PointerTo_wsa3__ReplyTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa3__ReplyTo(soap, data), 0) || soap_put_PointerTo_wsa3__ReplyTo(soap, data, "wsa3:ReplyTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa3__ReplyTo(struct soap*, struct wsa3__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa3__ReplyTo
#define soap_read_PointerTo_wsa3__ReplyTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa3__ReplyTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa3__ReplyTo(struct soap*, struct wsa3__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa3__From
#define SOAP_TYPE_PointerTo_wsa3__From (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa3__From(struct soap*, struct wsa3__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa3__From(struct soap*, const char *, int, struct wsa3__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa3__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa3__From(struct soap*, const char*, struct wsa3__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa3__From
#define soap_write_PointerTo_wsa3__From(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa3__From(soap, data), 0) || soap_put_PointerTo_wsa3__From(soap, data, "wsa3:From", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa3__From(struct soap*, struct wsa3__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa3__From
#define soap_read_PointerTo_wsa3__From(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa3__From(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa3__From(struct soap*, struct wsa3__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa3__RelatesTo
#define SOAP_TYPE_PointerTo_wsa3__RelatesTo (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa3__RelatesTo(struct soap*, struct wsa3__Relationship *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa3__RelatesTo(struct soap*, const char *, int, struct wsa3__Relationship *const*, const char *);
SOAP_FMAC3 struct wsa3__Relationship ** SOAP_FMAC4 soap_in_PointerTo_wsa3__RelatesTo(struct soap*, const char*, struct wsa3__Relationship **, const char*);

#ifndef soap_write_PointerTo_wsa3__RelatesTo
#define soap_write_PointerTo_wsa3__RelatesTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa3__RelatesTo(soap, data), 0) || soap_put_PointerTo_wsa3__RelatesTo(soap, data, "wsa3:RelatesTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa3__RelatesTo(struct soap*, struct wsa3__Relationship *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa3__RelatesTo
#define soap_read_PointerTo_wsa3__RelatesTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa3__RelatesTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__Relationship ** SOAP_FMAC4 soap_get_PointerTo_wsa3__RelatesTo(struct soap*, struct wsa3__Relationship **, const char*, const char*);

/* _wsa3__Action is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa3__Action
#define SOAP_TYPE__wsa3__Action (21)
#endif

#define soap_default__wsa3__Action(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa3__Action(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa3__Action soap_out_string


#define soap_in__wsa3__Action soap_in_string


#ifndef soap_write__wsa3__Action
#define soap_write__wsa3__Action(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__Action(soap, data), 0) || soap_put__wsa3__Action(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__Action soap_put_string


#ifndef soap_read__wsa3__Action
#define soap_read__wsa3__Action(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__Action(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__Action soap_get_string


/* _wsa3__To is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa3__To
#define SOAP_TYPE__wsa3__To (20)
#endif

#define soap_default__wsa3__To(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa3__To(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa3__To soap_out_string


#define soap_in__wsa3__To soap_in_string


#ifndef soap_write__wsa3__To
#define soap_write__wsa3__To(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__To(soap, data), 0) || soap_put__wsa3__To(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__To soap_put_string


#ifndef soap_read__wsa3__To
#define soap_read__wsa3__To(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__To(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__To soap_get_string


/* _wsa3__MessageID is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa3__MessageID
#define SOAP_TYPE__wsa3__MessageID (18)
#endif

#define soap_default__wsa3__MessageID(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa3__MessageID(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa3__MessageID soap_out_string


#define soap_in__wsa3__MessageID soap_in_string


#ifndef soap_write__wsa3__MessageID
#define soap_write__wsa3__MessageID(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa3__MessageID(soap, data), 0) || soap_put__wsa3__MessageID(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa3__MessageID soap_put_string


#ifndef soap_read__wsa3__MessageID
#define soap_read__wsa3__MessageID(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa3__MessageID(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa3__MessageID soap_get_string


#ifndef SOAP_TYPE_PointerTowsa3__ServiceNameType
#define SOAP_TYPE_PointerTowsa3__ServiceNameType (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa3__ServiceNameType(struct soap*, struct wsa3__ServiceNameType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa3__ServiceNameType(struct soap*, const char *, int, struct wsa3__ServiceNameType *const*, const char *);
SOAP_FMAC3 struct wsa3__ServiceNameType ** SOAP_FMAC4 soap_in_PointerTowsa3__ServiceNameType(struct soap*, const char*, struct wsa3__ServiceNameType **, const char*);

#ifndef soap_write_PointerTowsa3__ServiceNameType
#define soap_write_PointerTowsa3__ServiceNameType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa3__ServiceNameType(soap, data), 0) || soap_put_PointerTowsa3__ServiceNameType(soap, data, "wsa3:ServiceNameType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa3__ServiceNameType(struct soap*, struct wsa3__ServiceNameType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa3__ServiceNameType
#define soap_read_PointerTowsa3__ServiceNameType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa3__ServiceNameType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__ServiceNameType ** SOAP_FMAC4 soap_get_PointerTowsa3__ServiceNameType(struct soap*, struct wsa3__ServiceNameType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_QName
#define SOAP_TYPE_PointerTo_QName (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_QName(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_QName(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTo_QName(struct soap*, const char*, char ***, const char*);

#ifndef soap_write_PointerTo_QName
#define soap_write_PointerTo_QName(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_QName(soap, data), 0) || soap_put_PointerTo_QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_QName(struct soap*, char **const*, const char*, const char*);

#ifndef soap_read_PointerTo_QName
#define soap_read_PointerTo_QName(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTo_QName(struct soap*, char ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTowsa3__ReferencePropertiesType
#define SOAP_TYPE_PointerTowsa3__ReferencePropertiesType (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa3__ReferencePropertiesType(struct soap*, struct wsa3__ReferencePropertiesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa3__ReferencePropertiesType(struct soap*, const char *, int, struct wsa3__ReferencePropertiesType *const*, const char *);
SOAP_FMAC3 struct wsa3__ReferencePropertiesType ** SOAP_FMAC4 soap_in_PointerTowsa3__ReferencePropertiesType(struct soap*, const char*, struct wsa3__ReferencePropertiesType **, const char*);

#ifndef soap_write_PointerTowsa3__ReferencePropertiesType
#define soap_write_PointerTowsa3__ReferencePropertiesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa3__ReferencePropertiesType(soap, data), 0) || soap_put_PointerTowsa3__ReferencePropertiesType(soap, data, "wsa3:ReferencePropertiesType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa3__ReferencePropertiesType(struct soap*, struct wsa3__ReferencePropertiesType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa3__ReferencePropertiesType
#define soap_read_PointerTowsa3__ReferencePropertiesType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa3__ReferencePropertiesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa3__ReferencePropertiesType ** SOAP_FMAC4 soap_get_PointerTowsa3__ReferencePropertiesType(struct soap*, struct wsa3__ReferencePropertiesType **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOf_XML
#define SOAP_TYPE_std__vectorTemplateOf_XML (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOf_XML(struct soap*, std::vector<char * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOf_XML(struct soap*, const std::vector<char * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOf_XML(struct soap*, const char*, int, const std::vector<char * >*, const char*);
SOAP_FMAC3 std::vector<char * >* SOAP_FMAC4 soap_in_std__vectorTemplateOf_XML(struct soap*, const char*, std::vector<char * >*, const char*);

#define soap_new_std__vectorTemplateOf_XML(soap, n) soap_instantiate_std__vectorTemplateOf_XML(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOf_XML(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<char * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOf_XML(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOf_XML(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
