/* AnalyticsAnalyticsEngineBindingProxy.h
   Generated by gSOAP 2.8.0 from ./libonvif/analytics.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef AnalyticsAnalyticsEngineBindingProxy_H
#define AnalyticsAnalyticsEngineBindingProxy_H
#include "AnalyticsH.h"

class SOAP_CMAC AnalyticsEngineBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'AnalyticsEngineBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	AnalyticsEngineBindingProxy();
	/// Constructor with copy of another engine state
	AnalyticsEngineBindingProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	AnalyticsEngineBindingProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	AnalyticsEngineBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~AnalyticsEngineBindingProxy();
	/// Initializer used by constructors
	virtual	void AnalyticsEngineBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetSupportedAnalyticsModules' (returns error code or SOAP_OK)
	virtual	int GetSupportedAnalyticsModules(_tan__GetSupportedAnalyticsModules *tan__GetSupportedAnalyticsModules, _tan__GetSupportedAnalyticsModulesResponse *tan__GetSupportedAnalyticsModulesResponse);

	/// Web service operation 'CreateAnalyticsModules' (returns error code or SOAP_OK)
	virtual	int CreateAnalyticsModules(_tan__CreateAnalyticsModules *tan__CreateAnalyticsModules, _tan__CreateAnalyticsModulesResponse *tan__CreateAnalyticsModulesResponse);

	/// Web service operation 'DeleteAnalyticsModules' (returns error code or SOAP_OK)
	virtual	int DeleteAnalyticsModules(_tan__DeleteAnalyticsModules *tan__DeleteAnalyticsModules, _tan__DeleteAnalyticsModulesResponse *tan__DeleteAnalyticsModulesResponse);

	/// Web service operation 'GetAnalyticsModules' (returns error code or SOAP_OK)
	virtual	int GetAnalyticsModules(_tan__GetAnalyticsModules *tan__GetAnalyticsModules, _tan__GetAnalyticsModulesResponse *tan__GetAnalyticsModulesResponse);

	/// Web service operation 'ModifyAnalyticsModules' (returns error code or SOAP_OK)
	virtual	int ModifyAnalyticsModules(_tan__ModifyAnalyticsModules *tan__ModifyAnalyticsModules, _tan__ModifyAnalyticsModulesResponse *tan__ModifyAnalyticsModulesResponse);
};
#endif
