/* soapH.h
   Generated by gSOAP 2.8.0 from SMC.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_server__setCameraURI
#define SOAP_TYPE_server__setCameraURI (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_server__setCameraURI(struct soap*, struct server__setCameraURI *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_server__setCameraURI(struct soap*, const struct server__setCameraURI *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_server__setCameraURI(struct soap*, const char*, int, const struct server__setCameraURI *, const char*);
SOAP_FMAC3 struct server__setCameraURI * SOAP_FMAC4 soap_in_server__setCameraURI(struct soap*, const char*, struct server__setCameraURI *, const char*);

#ifndef soap_write_server__setCameraURI
#define soap_write_server__setCameraURI(soap, data) ( soap_begin_send(soap) || (soap_serialize_server__setCameraURI(soap, data), 0) || soap_put_server__setCameraURI(soap, data, "server:setCameraURI", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_server__setCameraURI(struct soap*, const struct server__setCameraURI *, const char*, const char*);

#ifndef soap_read_server__setCameraURI
#define soap_read_server__setCameraURI(soap, data) ( soap_begin_recv(soap) || !soap_get_server__setCameraURI(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct server__setCameraURI * SOAP_FMAC4 soap_get_server__setCameraURI(struct soap*, struct server__setCameraURI *, const char*, const char*);

#define soap_new_server__setCameraURI(soap, n) soap_instantiate_server__setCameraURI(soap, n, NULL, NULL, NULL)


#define soap_delete_server__setCameraURI(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct server__setCameraURI * SOAP_FMAC2 soap_instantiate_server__setCameraURI(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_server__setCameraURI(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_server__setCameraURIResponse
#define SOAP_TYPE_server__setCameraURIResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_server__setCameraURIResponse(struct soap*, struct server__setCameraURIResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_server__setCameraURIResponse(struct soap*, const struct server__setCameraURIResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_server__setCameraURIResponse(struct soap*, const char*, int, const struct server__setCameraURIResponse *, const char*);
SOAP_FMAC3 struct server__setCameraURIResponse * SOAP_FMAC4 soap_in_server__setCameraURIResponse(struct soap*, const char*, struct server__setCameraURIResponse *, const char*);

#ifndef soap_write_server__setCameraURIResponse
#define soap_write_server__setCameraURIResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_server__setCameraURIResponse(soap, data), 0) || soap_put_server__setCameraURIResponse(soap, data, "server:setCameraURIResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_server__setCameraURIResponse(struct soap*, const struct server__setCameraURIResponse *, const char*, const char*);

#ifndef soap_read_server__setCameraURIResponse
#define soap_read_server__setCameraURIResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_server__setCameraURIResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct server__setCameraURIResponse * SOAP_FMAC4 soap_get_server__setCameraURIResponse(struct soap*, struct server__setCameraURIResponse *, const char*, const char*);

#define soap_new_server__setCameraURIResponse(soap, n) soap_instantiate_server__setCameraURIResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_server__setCameraURIResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct server__setCameraURIResponse * SOAP_FMAC2 soap_instantiate_server__setCameraURIResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_server__setCameraURIResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_server__getinfo
#define SOAP_TYPE_server__getinfo (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_server__getinfo(struct soap*, struct server__getinfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_server__getinfo(struct soap*, const struct server__getinfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_server__getinfo(struct soap*, const char*, int, const struct server__getinfo *, const char*);
SOAP_FMAC3 struct server__getinfo * SOAP_FMAC4 soap_in_server__getinfo(struct soap*, const char*, struct server__getinfo *, const char*);

#ifndef soap_write_server__getinfo
#define soap_write_server__getinfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_server__getinfo(soap, data), 0) || soap_put_server__getinfo(soap, data, "server:getinfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_server__getinfo(struct soap*, const struct server__getinfo *, const char*, const char*);

#ifndef soap_read_server__getinfo
#define soap_read_server__getinfo(soap, data) ( soap_begin_recv(soap) || !soap_get_server__getinfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct server__getinfo * SOAP_FMAC4 soap_get_server__getinfo(struct soap*, struct server__getinfo *, const char*, const char*);

#define soap_new_server__getinfo(soap, n) soap_instantiate_server__getinfo(soap, n, NULL, NULL, NULL)


#define soap_delete_server__getinfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct server__getinfo * SOAP_FMAC2 soap_instantiate_server__getinfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_server__getinfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_server__getinfoResponse
#define SOAP_TYPE_server__getinfoResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_server__getinfoResponse(struct soap*, struct server__getinfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_server__getinfoResponse(struct soap*, const struct server__getinfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_server__getinfoResponse(struct soap*, const char*, int, const struct server__getinfoResponse *, const char*);
SOAP_FMAC3 struct server__getinfoResponse * SOAP_FMAC4 soap_in_server__getinfoResponse(struct soap*, const char*, struct server__getinfoResponse *, const char*);

#ifndef soap_write_server__getinfoResponse
#define soap_write_server__getinfoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_server__getinfoResponse(soap, data), 0) || soap_put_server__getinfoResponse(soap, data, "server:getinfoResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_server__getinfoResponse(struct soap*, const struct server__getinfoResponse *, const char*, const char*);

#ifndef soap_read_server__getinfoResponse
#define soap_read_server__getinfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_server__getinfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct server__getinfoResponse * SOAP_FMAC4 soap_get_server__getinfoResponse(struct soap*, struct server__getinfoResponse *, const char*, const char*);

#define soap_new_server__getinfoResponse(soap, n) soap_instantiate_server__getinfoResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_server__getinfoResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct server__getinfoResponse * SOAP_FMAC2 soap_instantiate_server__getinfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_server__getinfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__setCameraURI
#define SOAP_TYPE_agent__setCameraURI (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__setCameraURI(struct soap*, struct agent__setCameraURI *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__setCameraURI(struct soap*, const struct agent__setCameraURI *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__setCameraURI(struct soap*, const char*, int, const struct agent__setCameraURI *, const char*);
SOAP_FMAC3 struct agent__setCameraURI * SOAP_FMAC4 soap_in_agent__setCameraURI(struct soap*, const char*, struct agent__setCameraURI *, const char*);

#ifndef soap_write_agent__setCameraURI
#define soap_write_agent__setCameraURI(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__setCameraURI(soap, data), 0) || soap_put_agent__setCameraURI(soap, data, "agent:setCameraURI", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__setCameraURI(struct soap*, const struct agent__setCameraURI *, const char*, const char*);

#ifndef soap_read_agent__setCameraURI
#define soap_read_agent__setCameraURI(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__setCameraURI(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__setCameraURI * SOAP_FMAC4 soap_get_agent__setCameraURI(struct soap*, struct agent__setCameraURI *, const char*, const char*);

#define soap_new_agent__setCameraURI(soap, n) soap_instantiate_agent__setCameraURI(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__setCameraURI(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__setCameraURI * SOAP_FMAC2 soap_instantiate_agent__setCameraURI(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__setCameraURI(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__setCameraURIResponse
#define SOAP_TYPE_agent__setCameraURIResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__setCameraURIResponse(struct soap*, struct agent__setCameraURIResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__setCameraURIResponse(struct soap*, const struct agent__setCameraURIResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__setCameraURIResponse(struct soap*, const char*, int, const struct agent__setCameraURIResponse *, const char*);
SOAP_FMAC3 struct agent__setCameraURIResponse * SOAP_FMAC4 soap_in_agent__setCameraURIResponse(struct soap*, const char*, struct agent__setCameraURIResponse *, const char*);

#ifndef soap_write_agent__setCameraURIResponse
#define soap_write_agent__setCameraURIResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__setCameraURIResponse(soap, data), 0) || soap_put_agent__setCameraURIResponse(soap, data, "agent:setCameraURIResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__setCameraURIResponse(struct soap*, const struct agent__setCameraURIResponse *, const char*, const char*);

#ifndef soap_read_agent__setCameraURIResponse
#define soap_read_agent__setCameraURIResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__setCameraURIResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__setCameraURIResponse * SOAP_FMAC4 soap_get_agent__setCameraURIResponse(struct soap*, struct agent__setCameraURIResponse *, const char*, const char*);

#define soap_new_agent__setCameraURIResponse(soap, n) soap_instantiate_agent__setCameraURIResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__setCameraURIResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__setCameraURIResponse * SOAP_FMAC2 soap_instantiate_agent__setCameraURIResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__setCameraURIResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__setCameraInfo
#define SOAP_TYPE_agent__setCameraInfo (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__setCameraInfo(struct soap*, struct agent__setCameraInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__setCameraInfo(struct soap*, const struct agent__setCameraInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__setCameraInfo(struct soap*, const char*, int, const struct agent__setCameraInfo *, const char*);
SOAP_FMAC3 struct agent__setCameraInfo * SOAP_FMAC4 soap_in_agent__setCameraInfo(struct soap*, const char*, struct agent__setCameraInfo *, const char*);

#ifndef soap_write_agent__setCameraInfo
#define soap_write_agent__setCameraInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__setCameraInfo(soap, data), 0) || soap_put_agent__setCameraInfo(soap, data, "agent:setCameraInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__setCameraInfo(struct soap*, const struct agent__setCameraInfo *, const char*, const char*);

#ifndef soap_read_agent__setCameraInfo
#define soap_read_agent__setCameraInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__setCameraInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__setCameraInfo * SOAP_FMAC4 soap_get_agent__setCameraInfo(struct soap*, struct agent__setCameraInfo *, const char*, const char*);

#define soap_new_agent__setCameraInfo(soap, n) soap_instantiate_agent__setCameraInfo(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__setCameraInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__setCameraInfo * SOAP_FMAC2 soap_instantiate_agent__setCameraInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__setCameraInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__setCameraInfoResponse
#define SOAP_TYPE_agent__setCameraInfoResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__setCameraInfoResponse(struct soap*, struct agent__setCameraInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__setCameraInfoResponse(struct soap*, const struct agent__setCameraInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__setCameraInfoResponse(struct soap*, const char*, int, const struct agent__setCameraInfoResponse *, const char*);
SOAP_FMAC3 struct agent__setCameraInfoResponse * SOAP_FMAC4 soap_in_agent__setCameraInfoResponse(struct soap*, const char*, struct agent__setCameraInfoResponse *, const char*);

#ifndef soap_write_agent__setCameraInfoResponse
#define soap_write_agent__setCameraInfoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__setCameraInfoResponse(soap, data), 0) || soap_put_agent__setCameraInfoResponse(soap, data, "agent:setCameraInfoResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__setCameraInfoResponse(struct soap*, const struct agent__setCameraInfoResponse *, const char*, const char*);

#ifndef soap_read_agent__setCameraInfoResponse
#define soap_read_agent__setCameraInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__setCameraInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__setCameraInfoResponse * SOAP_FMAC4 soap_get_agent__setCameraInfoResponse(struct soap*, struct agent__setCameraInfoResponse *, const char*, const char*);

#define soap_new_agent__setCameraInfoResponse(soap, n) soap_instantiate_agent__setCameraInfoResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__setCameraInfoResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__setCameraInfoResponse * SOAP_FMAC2 soap_instantiate_agent__setCameraInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__setCameraInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__removeCamera
#define SOAP_TYPE_agent__removeCamera (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__removeCamera(struct soap*, struct agent__removeCamera *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__removeCamera(struct soap*, const struct agent__removeCamera *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__removeCamera(struct soap*, const char*, int, const struct agent__removeCamera *, const char*);
SOAP_FMAC3 struct agent__removeCamera * SOAP_FMAC4 soap_in_agent__removeCamera(struct soap*, const char*, struct agent__removeCamera *, const char*);

#ifndef soap_write_agent__removeCamera
#define soap_write_agent__removeCamera(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__removeCamera(soap, data), 0) || soap_put_agent__removeCamera(soap, data, "agent:removeCamera", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__removeCamera(struct soap*, const struct agent__removeCamera *, const char*, const char*);

#ifndef soap_read_agent__removeCamera
#define soap_read_agent__removeCamera(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__removeCamera(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__removeCamera * SOAP_FMAC4 soap_get_agent__removeCamera(struct soap*, struct agent__removeCamera *, const char*, const char*);

#define soap_new_agent__removeCamera(soap, n) soap_instantiate_agent__removeCamera(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__removeCamera(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__removeCamera * SOAP_FMAC2 soap_instantiate_agent__removeCamera(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__removeCamera(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__removeCameraResponse
#define SOAP_TYPE_agent__removeCameraResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__removeCameraResponse(struct soap*, struct agent__removeCameraResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__removeCameraResponse(struct soap*, const struct agent__removeCameraResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__removeCameraResponse(struct soap*, const char*, int, const struct agent__removeCameraResponse *, const char*);
SOAP_FMAC3 struct agent__removeCameraResponse * SOAP_FMAC4 soap_in_agent__removeCameraResponse(struct soap*, const char*, struct agent__removeCameraResponse *, const char*);

#ifndef soap_write_agent__removeCameraResponse
#define soap_write_agent__removeCameraResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__removeCameraResponse(soap, data), 0) || soap_put_agent__removeCameraResponse(soap, data, "agent:removeCameraResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__removeCameraResponse(struct soap*, const struct agent__removeCameraResponse *, const char*, const char*);

#ifndef soap_read_agent__removeCameraResponse
#define soap_read_agent__removeCameraResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__removeCameraResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__removeCameraResponse * SOAP_FMAC4 soap_get_agent__removeCameraResponse(struct soap*, struct agent__removeCameraResponse *, const char*, const char*);

#define soap_new_agent__removeCameraResponse(soap, n) soap_instantiate_agent__removeCameraResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__removeCameraResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__removeCameraResponse * SOAP_FMAC2 soap_instantiate_agent__removeCameraResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__removeCameraResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__addCamera
#define SOAP_TYPE_agent__addCamera (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__addCamera(struct soap*, struct agent__addCamera *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__addCamera(struct soap*, const struct agent__addCamera *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__addCamera(struct soap*, const char*, int, const struct agent__addCamera *, const char*);
SOAP_FMAC3 struct agent__addCamera * SOAP_FMAC4 soap_in_agent__addCamera(struct soap*, const char*, struct agent__addCamera *, const char*);

#ifndef soap_write_agent__addCamera
#define soap_write_agent__addCamera(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__addCamera(soap, data), 0) || soap_put_agent__addCamera(soap, data, "agent:addCamera", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__addCamera(struct soap*, const struct agent__addCamera *, const char*, const char*);

#ifndef soap_read_agent__addCamera
#define soap_read_agent__addCamera(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__addCamera(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__addCamera * SOAP_FMAC4 soap_get_agent__addCamera(struct soap*, struct agent__addCamera *, const char*, const char*);

#define soap_new_agent__addCamera(soap, n) soap_instantiate_agent__addCamera(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__addCamera(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__addCamera * SOAP_FMAC2 soap_instantiate_agent__addCamera(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__addCamera(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__addCameraResponse
#define SOAP_TYPE_agent__addCameraResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__addCameraResponse(struct soap*, struct agent__addCameraResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__addCameraResponse(struct soap*, const struct agent__addCameraResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__addCameraResponse(struct soap*, const char*, int, const struct agent__addCameraResponse *, const char*);
SOAP_FMAC3 struct agent__addCameraResponse * SOAP_FMAC4 soap_in_agent__addCameraResponse(struct soap*, const char*, struct agent__addCameraResponse *, const char*);

#ifndef soap_write_agent__addCameraResponse
#define soap_write_agent__addCameraResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__addCameraResponse(soap, data), 0) || soap_put_agent__addCameraResponse(soap, data, "agent:addCameraResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__addCameraResponse(struct soap*, const struct agent__addCameraResponse *, const char*, const char*);

#ifndef soap_read_agent__addCameraResponse
#define soap_read_agent__addCameraResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__addCameraResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__addCameraResponse * SOAP_FMAC4 soap_get_agent__addCameraResponse(struct soap*, struct agent__addCameraResponse *, const char*, const char*);

#define soap_new_agent__addCameraResponse(soap, n) soap_instantiate_agent__addCameraResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__addCameraResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__addCameraResponse * SOAP_FMAC2 soap_instantiate_agent__addCameraResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__addCameraResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__coreStation
#define SOAP_TYPE_agent__coreStation (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__coreStation(struct soap*, struct agent__coreStation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__coreStation(struct soap*, const struct agent__coreStation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__coreStation(struct soap*, const char*, int, const struct agent__coreStation *, const char*);
SOAP_FMAC3 struct agent__coreStation * SOAP_FMAC4 soap_in_agent__coreStation(struct soap*, const char*, struct agent__coreStation *, const char*);

#ifndef soap_write_agent__coreStation
#define soap_write_agent__coreStation(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__coreStation(soap, data), 0) || soap_put_agent__coreStation(soap, data, "agent:coreStation", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__coreStation(struct soap*, const struct agent__coreStation *, const char*, const char*);

#ifndef soap_read_agent__coreStation
#define soap_read_agent__coreStation(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__coreStation(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__coreStation * SOAP_FMAC4 soap_get_agent__coreStation(struct soap*, struct agent__coreStation *, const char*, const char*);

#define soap_new_agent__coreStation(soap, n) soap_instantiate_agent__coreStation(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__coreStation(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__coreStation * SOAP_FMAC2 soap_instantiate_agent__coreStation(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__coreStation(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_agent__coreStationResponse
#define SOAP_TYPE_agent__coreStationResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_agent__coreStationResponse(struct soap*, struct agent__coreStationResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_agent__coreStationResponse(struct soap*, const struct agent__coreStationResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_agent__coreStationResponse(struct soap*, const char*, int, const struct agent__coreStationResponse *, const char*);
SOAP_FMAC3 struct agent__coreStationResponse * SOAP_FMAC4 soap_in_agent__coreStationResponse(struct soap*, const char*, struct agent__coreStationResponse *, const char*);

#ifndef soap_write_agent__coreStationResponse
#define soap_write_agent__coreStationResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_agent__coreStationResponse(soap, data), 0) || soap_put_agent__coreStationResponse(soap, data, "agent:coreStationResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_agent__coreStationResponse(struct soap*, const struct agent__coreStationResponse *, const char*, const char*);

#ifndef soap_read_agent__coreStationResponse
#define soap_read_agent__coreStationResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_agent__coreStationResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct agent__coreStationResponse * SOAP_FMAC4 soap_get_agent__coreStationResponse(struct soap*, struct agent__coreStationResponse *, const char*, const char*);

#define soap_new_agent__coreStationResponse(soap, n) soap_instantiate_agent__coreStationResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_agent__coreStationResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct agent__coreStationResponse * SOAP_FMAC2 soap_instantiate_agent__coreStationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_agent__coreStationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_camera__info
#define SOAP_TYPE_camera__info (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_camera__info(struct soap*, struct camera__info *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_camera__info(struct soap*, const struct camera__info *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_camera__info(struct soap*, const char*, int, const struct camera__info *, const char*);
SOAP_FMAC3 struct camera__info * SOAP_FMAC4 soap_in_camera__info(struct soap*, const char*, struct camera__info *, const char*);

#ifndef soap_write_camera__info
#define soap_write_camera__info(soap, data) ( soap_begin_send(soap) || (soap_serialize_camera__info(soap, data), 0) || soap_put_camera__info(soap, data, "camera:info", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_camera__info(struct soap*, const struct camera__info *, const char*, const char*);

#ifndef soap_read_camera__info
#define soap_read_camera__info(soap, data) ( soap_begin_recv(soap) || !soap_get_camera__info(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct camera__info * SOAP_FMAC4 soap_get_camera__info(struct soap*, struct camera__info *, const char*, const char*);

#define soap_new_camera__info(soap, n) soap_instantiate_camera__info(soap, n, NULL, NULL, NULL)


#define soap_delete_camera__info(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct camera__info * SOAP_FMAC2 soap_instantiate_camera__info(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_camera__info(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_camera__uri
#define SOAP_TYPE_camera__uri (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_camera__uri(struct soap*, struct camera__uri *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_camera__uri(struct soap*, const struct camera__uri *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_camera__uri(struct soap*, const char*, int, const struct camera__uri *, const char*);
SOAP_FMAC3 struct camera__uri * SOAP_FMAC4 soap_in_camera__uri(struct soap*, const char*, struct camera__uri *, const char*);

#ifndef soap_write_camera__uri
#define soap_write_camera__uri(soap, data) ( soap_begin_send(soap) || (soap_serialize_camera__uri(soap, data), 0) || soap_put_camera__uri(soap, data, "camera:uri", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_camera__uri(struct soap*, const struct camera__uri *, const char*, const char*);

#ifndef soap_read_camera__uri
#define soap_read_camera__uri(soap, data) ( soap_begin_recv(soap) || !soap_get_camera__uri(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct camera__uri * SOAP_FMAC4 soap_get_camera__uri(struct soap*, struct camera__uri *, const char*, const char*);

#define soap_new_camera__uri(soap, n) soap_instantiate_camera__uri(soap, n, NULL, NULL, NULL)


#define soap_delete_camera__uri(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct camera__uri * SOAP_FMAC2 soap_instantiate_camera__uri(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_camera__uri(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTocamera__uri
#define SOAP_TYPE_PointerTocamera__uri (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocamera__uri(struct soap*, struct camera__uri *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocamera__uri(struct soap*, const char *, int, struct camera__uri *const*, const char *);
SOAP_FMAC3 struct camera__uri ** SOAP_FMAC4 soap_in_PointerTocamera__uri(struct soap*, const char*, struct camera__uri **, const char*);

#ifndef soap_write_PointerTocamera__uri
#define soap_write_PointerTocamera__uri(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTocamera__uri(soap, data), 0) || soap_put_PointerTocamera__uri(soap, data, "camera:uri", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocamera__uri(struct soap*, struct camera__uri *const*, const char*, const char*);

#ifndef soap_read_PointerTocamera__uri
#define soap_read_PointerTocamera__uri(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTocamera__uri(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct camera__uri ** SOAP_FMAC4 soap_get_PointerTocamera__uri(struct soap*, struct camera__uri **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTocamera__info
#define SOAP_TYPE_PointerTocamera__info (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocamera__info(struct soap*, struct camera__info *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocamera__info(struct soap*, const char *, int, struct camera__info *const*, const char *);
SOAP_FMAC3 struct camera__info ** SOAP_FMAC4 soap_in_PointerTocamera__info(struct soap*, const char*, struct camera__info **, const char*);

#ifndef soap_write_PointerTocamera__info
#define soap_write_PointerTocamera__info(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTocamera__info(soap, data), 0) || soap_put_PointerTocamera__info(soap, data, "camera:info", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocamera__info(struct soap*, struct camera__info *const*, const char*, const char*);

#ifndef soap_read_PointerTocamera__info
#define soap_read_PointerTocamera__info(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTocamera__info(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct camera__info ** SOAP_FMAC4 soap_get_PointerTocamera__info(struct soap*, struct camera__info **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
