/* soapserverService.cpp
   Generated by gSOAP 2.8.0 from SMC.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#include "soapserverService.h"

serverService::serverService()
{	serverService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

serverService::serverService(const struct soap &_soap) :soap(_soap)
{ }

serverService::serverService(soap_mode iomode)
{	serverService_init(iomode, iomode);
}

serverService::serverService(soap_mode imode, soap_mode omode)
{	serverService_init(imode, omode);
}

serverService::~serverService()
{ }

void serverService::serverService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"camera", "http://tempuri.org/camera.xsd", NULL, NULL},
	{"agent", "http://tempuri.org/agent.xsd", NULL, NULL},
	{"server", "http://tempuri.org/server.xsd", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	this->namespaces = namespaces;
};

void serverService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

serverService *serverService::copy()
{	serverService *dup = SOAP_NEW_COPY(serverService(*(struct soap*)this));
	return dup;
}

int serverService::soap_close_socket()
{	return soap_closesock(this);
}

int serverService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int serverService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int serverService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int serverService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void serverService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void serverService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *serverService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void serverService::soap_noheader()
{	header = NULL;
}

int serverService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()))
				return this->error;
			(void)serve();
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET serverService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET serverService::accept()
{	return soap_accept(this);
}

int serverService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{	soap_begin(this);
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			this->error = SOAP_EOF;
			return soap_send_fault(this);
		}
#endif

		soap_begin(this);

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_recv(this))
		{	if (this->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(this);
#else 
				return soap_send_fault(this);
#endif
			}
			soap_closesock(this);

			continue;
		}

		if (soap_envelope_begin_in(this)
		 || soap_recv_header(this)
		 || soap_body_begin_in(this)
		 || dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_server__getinfo(serverService*);
static int serve_server__setCameraURI(serverService*);

int serverService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "server:getinfo"))
		return serve_server__getinfo(this);
	if (!soap_match_tag(this, this->tag, "server:setCameraURI"))
		return serve_server__setCameraURI(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_server__getinfo(serverService *soap)
{	struct server__getinfo soap_tmp_server__getinfo;
	struct server__getinfoResponse soap_tmp_server__getinfoResponse;
	soap_default_server__getinfoResponse(soap, &soap_tmp_server__getinfoResponse);
	soap_default_server__getinfo(soap, &soap_tmp_server__getinfo);
	soap->encodingStyle = NULL;
	if (!soap_get_server__getinfo(soap, &soap_tmp_server__getinfo, "server:getinfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->getinfo(soap_tmp_server__getinfo.command, soap_tmp_server__getinfoResponse.message);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_server__getinfoResponse(soap, &soap_tmp_server__getinfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_server__getinfoResponse(soap, &soap_tmp_server__getinfoResponse, "server:getinfoResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_server__getinfoResponse(soap, &soap_tmp_server__getinfoResponse, "server:getinfoResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_server__setCameraURI(serverService *soap)
{	struct server__setCameraURI soap_tmp_server__setCameraURI;
	struct server__setCameraURIResponse soap_tmp_server__setCameraURIResponse;
	soap_default_server__setCameraURIResponse(soap, &soap_tmp_server__setCameraURIResponse);
	soap_default_server__setCameraURI(soap, &soap_tmp_server__setCameraURI);
	soap->encodingStyle = NULL;
	if (!soap_get_server__setCameraURI(soap, &soap_tmp_server__setCameraURI, "server:setCameraURI", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->setCameraURI(soap_tmp_server__setCameraURI._info, soap_tmp_server__setCameraURIResponse.message);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_server__setCameraURIResponse(soap, &soap_tmp_server__setCameraURIResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_server__setCameraURIResponse(soap, &soap_tmp_server__setCameraURIResponse, "server:setCameraURIResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_server__setCameraURIResponse(soap, &soap_tmp_server__setCameraURIResponse, "server:setCameraURIResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
