/* soapagentProxy.h
   Generated by gSOAP 2.8.0 from SMC.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapagentProxy_H
#define soapagentProxy_H
#include "soapH.h"

class SOAP_CMAC agentProxy : public soap
{ public:
	/// Endpoint URL of service 'agentProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	agentProxy();
	/// Constructor with copy of another engine state
	agentProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	agentProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	agentProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~agentProxy();
	/// Initializer used by constructors
	virtual	void agentProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'coreStation' (returns error code or SOAP_OK)
	virtual	int coreStation(std::string command, std::string &message);

	/// Web service operation 'addCamera' (returns error code or SOAP_OK)
	virtual	int addCamera(std::string uuid, std::string &message);

	/// Web service operation 'removeCamera' (returns error code or SOAP_OK)
	virtual	int removeCamera(std::string uuid, std::string &message);

	/// Web service operation 'setCameraInfo' (returns error code or SOAP_OK)
	virtual	int setCameraInfo(struct camera__info *_info, std::string &message);

	/// Web service operation 'setCameraURI' (returns error code or SOAP_OK)
	virtual	int setCameraURI(struct camera__uri *_info, std::string &message);
};
#endif
